name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality:
    name: 代码质量检查
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 安装依赖
        run: yarn install --frozen-lockfile

      - name: 构建项目
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: TypeScript 类型检查
        run: yarn tsc --noEmit

      - name: ESLint 检查
        run: yarn lint

      - name: Prettier 格式检查
        run: yarn prettier --check .

      - name: 依赖包安全审计
        run: yarn npm audit

  test:
    name: 单元测试
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 安装依赖
        run: yarn install --frozen-lockfile

      - name: 运行测试
        run: yarn test
