name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # 缓存.contentlayer目录
    - name: Cache contentlayer
      uses: actions/cache@v3
      with:
        path: .contentlayer
        key: ${{ runner.os }}-contentlayer-${{ hashFiles('data/**') }}
        restore-keys: |
          ${{ runner.os }}-contentlayer-

    # 缓存.contentlayer目录
    - name: Cache contentlayer
      uses: actions/cache@v3
      with:
        path: .contentlayer
        key: ${{ runner.os }}-contentlayer-${{ hashFiles('data/**', 'contentlayer.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-contentlayer-

    # 生成contentlayer文件
    - name: Generate contentlayer files
      run: |
        echo "开始生成contentlayer文件..."
        yarn build
        echo "检查生成的文件："
        ls -la .contentlayer/generated || true
        
    # 执行类型检查
    - name: Type check
      run: |
        echo "开始类型检查..."
        yarn tsc --noEmit
        echo "类型检查完成"
    
    - name: Lint check
      run: yarn lint
    
    - name: Prettier check
      run: yarn prettier --check .
    
    - name: Security audit
      run: yarn npm audit