name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # 缓存.contentlayer目录
    - name: Cache contentlayer
      uses: actions/cache@v3
      with:
        path: .contentlayer
        key: ${{ runner.os }}-contentlayer-${{ hashFiles('data/**') }}
        restore-keys: |
          ${{ runner.os }}-contentlayer-

    # 先执行构建，这会自动生成contentlayer文件
    - name: Build project
      run: yarn build
      env:
        SKIP_BUILD_STATIC_GENERATION: true
    
    - name: Type check
      run: yarn tsc --noEmit
    
    - name: Lint check
      run: yarn lint
    
    - name: Prettier check
      run: yarn prettier --check .
    
    - name: Security audit
      run: yarn npm audit